
package com.nxp.csw_client_compe.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductService", targetNamespace = "http://service.csw_compe.nxp.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductService {


    /**
     * 
     * @return
     *     returns java.util.List<com.nxp.csw_client_compe.service.Product>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllProducts", targetNamespace = "http://service.csw_compe.nxp.com/", className = "com.nxp.csw_client_compe.service.GetAllProducts")
    @ResponseWrapper(localName = "getAllProductsResponse", targetNamespace = "http://service.csw_compe.nxp.com/", className = "com.nxp.csw_client_compe.service.GetAllProductsResponse")
    @Action(input = "http://service.csw_compe.nxp.com/ProductService/getAllProductsRequest", output = "http://service.csw_compe.nxp.com/ProductService/getAllProductsResponse")
    public List<Product> getAllProducts();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.nxp.csw_client_compe.service.Product
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllById", targetNamespace = "http://service.csw_compe.nxp.com/", className = "com.nxp.csw_client_compe.service.GetAllById")
    @ResponseWrapper(localName = "getAllByIdResponse", targetNamespace = "http://service.csw_compe.nxp.com/", className = "com.nxp.csw_client_compe.service.GetAllByIdResponse")
    @Action(input = "http://service.csw_compe.nxp.com/ProductService/getAllByIdRequest", output = "http://service.csw_compe.nxp.com/ProductService/getAllByIdResponse")
    public Product getAllById(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.nxp.csw_client_compe.service.Product
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addProduct", targetNamespace = "http://service.csw_compe.nxp.com/", className = "com.nxp.csw_client_compe.service.AddProduct")
    @ResponseWrapper(localName = "addProductResponse", targetNamespace = "http://service.csw_compe.nxp.com/", className = "com.nxp.csw_client_compe.service.AddProductResponse")
    @Action(input = "http://service.csw_compe.nxp.com/ProductService/addProductRequest", output = "http://service.csw_compe.nxp.com/ProductService/addProductResponse")
    public Product addProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        Product arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.nxp.csw_client_compe.service.Product
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sellProduct", targetNamespace = "http://service.csw_compe.nxp.com/", className = "com.nxp.csw_client_compe.service.SellProduct")
    @ResponseWrapper(localName = "sellProductResponse", targetNamespace = "http://service.csw_compe.nxp.com/", className = "com.nxp.csw_client_compe.service.SellProductResponse")
    @Action(input = "http://service.csw_compe.nxp.com/ProductService/sellProductRequest", output = "http://service.csw_compe.nxp.com/ProductService/sellProductResponse")
    public Product sellProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Long arg1);

}
